/* USER CODE BEGIN Header */
/******************************************************************************
* @file    main.h
* @brief   Main application definitions and includes
*
*          Contains global definitions, peripheral handles, and
*          application-wide configuration values.
*
*          This file is generated by STM32CubeMX and extended
*          with user-defined application content.
*
* @board   Custom STM32F446RE board
* @author  Alexandre Panhaleux
******************************************************************************/
/* USER CODE END Header */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32f4xx_hal.h" /* STM32 HAL core definitions */


/* Error handler prototype ---------------------------------------------------*/
void Error_Handler(void);


/* USART2 GPIO configuration -------------------------------------------------*/
#define USART_TX_Pin GPIO_PIN_2
#define USART_TX_GPIO_Port GPIOA
#define USART_RX_Pin GPIO_PIN_3
#define USART_RX_GPIO_Port GPIOA

/* SWD / Debug interface pins ------------------------------------------------*/
#define TMS_Pin GPIO_PIN_13
#define TMS_GPIO_Port GPIOA
#define TCK_Pin GPIO_PIN_14
#define TCK_GPIO_Port GPIOA
#define SWO_Pin GPIO_PIN_3
#define SWO_GPIO_Port GPIOB


#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
